---
Name: omnipay-logging
---
# Set up a separate logger name for omnipay, but map it to the default implementation
SilverStripe\Core\Injector\Injector:
  SilverStripe\Omnipay\Logger: '%$Psr\Log\LoggerInterface'

# Example how to set up a logger for omnipay that logs to a separate log-file named "omnipay.log"
# SilverStripe\Core\Injector\Injector:
#   SilverStripe\Omnipay\Logger:
#     type: singleton
#     class: Monolog\Logger
#     constructor:
#       - 'ss-omnipay-log'
#     calls:
#       pushLogFileHandler: [ pushHandler, [ %$OmnipayLogFileHandler ] ]
#   OmnipayLogFileHandler:
#     class: Monolog\Handler\StreamHandler
#     constructor:
#       - "../omnipay.log"
#       - "info"
