---
Name: omnipay-routes
After: framework/routes#coreroutes
---
SilverStripe\Control\Director:
  rules:
    'paymentendpoint' : SilverStripe\Omnipay\PaymentGatewayController
    'dev/payment' : SilverStripe\Omnipay\Admin\PaymentDevelopmentAdmin
