---
Name: omnipay-services
---
SilverStripe\Omnipay\Service\ServiceFactory:
  services:
    authorize: SilverStripe\Omnipay\Service\AuthorizeService
    createcard: SilverStripe\Omnipay\Service\CreateCardService
    purchase: SilverStripe\Omnipay\Service\PurchaseService
    refund: SilverStripe\Omnipay\Service\RefundService
    capture: SilverStripe\Omnipay\Service\CaptureService
    void: SilverStripe\Omnipay\Service\VoidService
